name: Transcrypt env file to ElasticBeanstalk
description: Add transcrypt encoded environnement file to ElasticBeanstalk

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  env_file:
    description: path to env file
    required: true
  eb_config_path:
    description: Path to Elastic Beanstalk config file
    required: false
    default: .ebextensions/options.config
  transcrypt_key:
    description: Transcrypt key
    required: true

runs:
  using: composite
  steps:
      - shell: bash
        run: git clone https://github.com/elasticdog/transcrypt.git
      - shell: bash
        run: transcrypt/transcrypt -c aes-256-cbc -p '${{ inputs.transcrypt_key }}' -y
      - shell: bash
        run: bash generate-eb-env.sh ${{ inputs.env_file }} ${{ inputs.eb_config_path }}
