name: Verify

on: push

jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: bash formatting
        run: docker run -v "$PWD":/mnt -w /mnt mvdan/shfmt -ci -- *.sh

      - name: shellcheck
        run: docker run -v "$PWD":/mnt -w /mnt koalaman/shellcheck -- *.sh test/*.bats

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local

      - name: Run Tests
        run: bats test/*.bats

  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    needs: [static_checks, tests]
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          env_file: test/.env
          transcrypt_key: s07Fjs/lwSJs+tpOZf2s9z0e0Ak6wpen/F3TqXPu
